spring:
  ai:
    mcp:
      server:
        name: webmvc-mcp-server
        version: 1.0.0
        type: ASYNC  # Recommended for reactive applications
        instructions: "This reactive server provides time information tools and resources"
        sse-message-endpoint: /mcp/messages
        capabilities:
          tool: true
          resource: true
          prompt: true
          completion: true

    alibaba:
      mcp:
        nacos:
          # 使用nacos public命名空间
          namespace: public
          # 注意这里前面docker启动 nacos的时候，将本机的7848 映射到了 nacos服务的8848 端口
          server-addr: 127.0.0.1:7848
          username: nacos
          password: G0aAv#kZ # 替换成自己的密码
          register:
            enabled: true
            service-group: mcp-server
            service-name: webmvc-mcp-server
logging:
  level:
    org.springframework.ai: debug
    org.springframework.web: DEBUG